### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by Xiphe** [filtercake/piggyback#11]
As a potential user I want to know what this is about

Given I visit the project/repo 
Then I expect the readme.md to onboard me in what problems this project is solving

**Comment by afknapping** [comment]
@Xiphe @escapedcat

that is correct :)

as described in #7:

> Communication of problems this thing should solve (eg 90 second video)
> Communication of how they can be solved (based on people, not tech) (another 90 second video)

and being worked out in #8 

---

a quick-and-dirty attempt from the hip:

> piggyback provides an adhoc, zero-config, encrypted interface for communication and collaboration that does not depoend on central services from the internet.
> it uses peer-to-peer technology via the local network to offer chat, filetransfer and a whiteboard.
> example usecases are: attendees of a conference, refugees in a camp, or neighbors in a city-block.
