### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by afknapping** [filtercake/piggyback#5]

**Comment by filtercake** [comment]
![image](https://user-images.githubusercontent.com/170145/34012509-5755e21e-e114-11e7-8ae5-0a7dfc0efe97.png)

**Comment by filtercake** [comment]
![image](https://user-images.githubusercontent.com/170145/36341637-98dcdd68-13f1-11e8-8920-a58db9f18775.png)

**Comment by afknapping** [comment]
![image](https://user-images.githubusercontent.com/170145/36352625-13ac21a0-14bc-11e8-9126-413e2c49f1f1.png)

**Comment by afknapping** [comment]
![image](https://user-images.githubusercontent.com/170145/36355766-706b856c-14e8-11e8-82ff-290d751d5568.png)
